/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rolledCarpet.gltf 
Author: sarpersoher (https://sketchfab.com/sarpersoher)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/carpet-4c04c67b817b4d9b8a0b52ba14359489
Title: Carpet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/rolledCarpet.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 1.3, 0.64, -0.5]} scale={2}>  
        <mesh geometry={nodes.Cube_0.geometry} material={materials.Material} position={[0, 0.193, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
      </group>
    </group>
  )
}
//1.1, 0.77, -0.16
useGLTF.preload('/rolledCarpet.gltf')
